services:
  open-webui:
    image: ghcr.io/open-webui/open-webui
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - ${USERPROFILE}/open-webui/data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATA_DIR=/app/backend/data
      - WEBUI_SECRET_KEY_FILE=/app/backend/data/.webui_secret_key